---
layout: page
title: Photin
output:
  md_document:
    variant: gfm
    preserve_yaml: TRUE
cover-img: ["assets/img/Aix200_loading.jpg", "assets/img/Aix200RF_heat_up_test.jpeg", "assets/img/G1/G1_cntrl.JPG", "assets/img/G1/G1_GB_cntrl.JPG", "assets/img/G1/G1_side.JPG"]
#subtitle: Europe, Poland, Warsaw area
---

The company aim is to provide dedicated, fast and flexible MOCVD wafer growth services to worldwide customers in R&D and small scale production of compound semiconductor devices (InP / GaAs/ GaSb/ InAs ).  
  
We are happy to support customers also in area of device simulation and epitaxial design of lasers, LEDs, detectors, and solar cells.   


```{r setup, include=FALSE}
library(stringr)
library(ggplot2)
library(rmarkdown)
library(knitr)

#cover-img: ../img/E0_with_bubblers.jpeg

```



```{r fig-options, include=FALSE}
base_dir <- "~/photin/beautiful-jekyll/" # i.e. where the jekyll blog is on the hard drive.
base_url <- "/" # keep as is

# If the document is currently being knit, do this; skip it in normal execution
if (!is.null(knitr::current_input())){
  
  # Output path for figures
  fig_path <- paste0("_site/assets/img/", str_remove(knitr::current_input(), ".Rmd"), "/")
  
  # Set base directories
  knitr::opts_knit$set(base.dir = base_dir, base.url = base_url)
  
  # Set figure directories
  knitr::opts_chunk$set(fig.path = fig_path,
                      cache.path = '../cache/',
                      message=FALSE, warning=FALSE,
                      cache = FALSE)
}
```
